# Generated by Django 5.2.6 on 2026-09-29 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_user_profile_unm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='unm',
            new_name='user',
        ),
    ]
